---
title: "Atividade 2"
author: "Jônatha Reis"
date: "2023-04-23"
output: html_document
---
```{=html}
<style>
body{
text-align:justify}
</style>
```

## Pacotes necessários 

```{r}
require(dplyr)
require(tidyr)
require(ggplot2)
require(validate)

```
##  Criando arquivos no sistema eMOF

```{r, include=TRUE, results='markup'}
iris <- read.csv("dados_unidosR.csv", header = T, sep = ";")
iris$x <- NULL
lapply(iris, unique)
str(iris)
```

## Inspeção visual da distribuição dos valores numéricos.
```{r}
iris %>% 
  select(spp, tamanho_petala:largura_sepala) %>% 
  pivot_longer(cols = -spp, names_to = "variavel", values_to = "valores") %>% 
  ggplot(aes(x = valores, fill = spp)) +
    geom_histogram() +
    facet_wrap(~ variavel, scales = 'free_x') +
    theme_classic() +
  theme(legend.position = "bottom") +
    labs(x = "tamanho (mm)") +
    scale_fill_discrete(
      expression(bold("spp:")),
      labels = c(expression(italic("Iris setosa")), 
                 expression(italic("Iris versicolor")), 
                 expression(italic("Iris virginica"))))

```


rules <- validator(in_range(lat, min = -90, max = 90),
                   in_range(lat, min = -180, max = 180),
                   is.character(site),
                   is.numeric(date),
                   all_complete(iris))

out   <- confront(iris, rules)
summary(out)
